name: Python codeqa/test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        python-version: ["2.7", "3.6", "3.9", "3.10", "pypy-2.7", "pypy-3.7"]
        exclude:
        - os: macos-11
          python-version: pypy-2.7
        - os: windows-latest
          python-version: "2.7"
        - os: windows-latest
          python-version: pypy-2.7
        - os: windows-latest
          python-version: pypy-3.7
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: MatteoH2O1999/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade setuptools
      run: pip install --force-reinstall --index-url 'https://eyJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2021-12-22T12:22:00.742810Z@time-machines-pypi.sealsecurity.io/' "setuptools >= 40.9"
    - name: Install the project
      run: "pip install --force-reinstall --index-url 'https://eyJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2021-12-22T12:22:00.742810Z@time-machines-pypi.sealsecurity.io/' --no-binary=:all: ."
    - name: Install test dependencies
      run: pip install --force-reinstall --index-url 'https://eyJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2021-12-22T12:22:00.742810Z@time-machines-pypi.sealsecurity.io/' .[test]
    - name: Test with pytest
      run: python -b -m pytest -W always --cov-report=xml:pytest-cov.xml
    - name: Send coverage data to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: pytest-cov.xml
