name: Build and upload artifacts

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: MatteoH2O1999/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --force-reinstall --index-url 'https://eyJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2021-12-22T12:22:00.742810Z@time-machines-pypi.sealsecurity.io/' "setuptools >= 40.9"
        pip install --force-reinstall --index-url 'https://eyJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2021-12-22T12:22:00.742810Z@time-machines-pypi.sealsecurity.io/' .
    - name: Create packages
      run: python setup.py sdist bdist_wheel
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: dist/*
